name: HTML CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display files
        run: ls -la

      - name: Success message
        run: echo "GitHub Action is running successfully"